Web Development/ASP.NET MVC/03. Kendo UI ASP.NET MVC Wrappers/KendoUI_ASP.NET_MVC_Wrappers/LibrarySystem/Controllers/LibrarySystemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using LibrarySystem.Models;
using LibrarySystem.Data;

namespace LibrarySystem.Controllers
{
    public class LibrarySystemController : BaseController
    {
        //private DataContext db = new DataContext();
        IUowData db;

        public LibrarySystemController()
            : base(null)
        {
            db = new UowData();
        }

        public LibrarySystemController(IUowData db)
            : base(db)
        {
        }


        // GET: /LibrarySystem/
        public ActionResult Index()
        {
            var result = this.db.Categories.All()
                .Include("Books").ToList()
                .Select(x => new TreeViewItemModel
                {
                    Text = x.Name,
                    //Id = x.CategoryId.ToString(),
                    Items = x.Books
                    .Select(y => new TreeViewItemModel
                    {
                        Text = y.Title,
                        Id = y.BookId.ToString()
                    }).ToList()
                });
            //var books = db.Books.All().Include(b => b.Category);
            //return View(books.ToList());
            return View(result);
        }

        // GET: /LibrarySystem/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.GetById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: /LibrarySystem/Search/someString
        // [ValidateAntiForgeryToken]
        //public ActionResult Search([DataSourceRequest] DataSourceRequest request,string book)
        public ActionResult Search(string book)
        {
            if (book == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var books = db.Books.All().Where(b => b.Title.Contains(book) ||
                b.Authors.Contains(book)).Select(BookShortVM.FromBook).ToList();
            if (books == null)
            {
                return HttpNotFound();
            }

            //var result = books.ToDataSourceResult(request, o => new BookViewModel()
            //{
            //    BookId = o.BookId,
            //    Title = o.Title,
            //    Authors = o.Authors,
            //    CategoryName = o.Category.Name
            //});

            return View("Search", books); //result.Data);
        }

        // GET: /LibrarySystem/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories.All(), "CategoryId", "Name");
            return View();
        }

        // POST: /LibrarySystem/Create
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories.All(), "CategoryId", "Name", book.CategoryId);
            return View(book);
        }

        // GET: /LibrarySystem/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.GetById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories.All(), "CategoryId", "Name", book.CategoryId);
            return View(book);
        }

        // POST: /LibrarySystem/Edit/5
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Update(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories.All(), "CategoryId", "Name", book.CategoryId);
            return View(book);
        }

        // GET: /LibrarySystem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.GetById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: /LibrarySystem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.GetById(id);
            db.Books.Delete(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web Development/ASP.NET MVC/03. Kendo UI ASP.NET MVC Wrappers/KendoUI_ASP.NET_MVC_Wrappers/LibrarySystem/Views/LibrarySystem/Create.cshtml
@model LibrarySystem.Models.Book

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>Book</legend>

        <div class="control-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Authors, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Authors)
                @Html.ValidationMessageFor(model => model.Authors, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.ISBN, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.ISBN)
                @Html.ValidationMessageFor(model => model.ISBN, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.WebSite, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.WebSite)
                @Html.ValidationMessageFor(model => model.WebSite, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("CategoryId", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryId, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Create" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to Books", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web Development/ASP.NET MVC/03. Kendo UI ASP.NET MVC Wrappers/KendoUI_ASP.NET_MVC_Wrappers/LibrarySystem/Views/LibrarySystem/Delete.cshtml
@model LibrarySystem.Models.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Book</legend>

    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Authors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Authors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebSite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebSite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn" /> |
        @Html.ActionLink("Back to Books", "Index")
    </div>
}

Web Development/ASP.NET MVC/03. Kendo UI ASP.NET MVC Wrappers/KendoUI_ASP.NET_MVC_Wrappers/LibrarySystem/Views/LibrarySystem/Details.cshtml
@model LibrarySystem.Models.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Book</legend>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Authors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Authors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebSite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebSite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.BookId }) |
    @Html.ActionLink("Back to Books", "Index")
</p>

Web Development/ASP.NET MVC/03. Kendo UI ASP.NET MVC Wrappers/KendoUI_ASP.NET_MVC_Wrappers/LibrarySystem/Views/LibrarySystem/Edit.cshtml
@model LibrarySystem.Models.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>Book</legend>

        @Html.HiddenFor(model => model.BookId)

        <div class="control-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Authors, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Authors)
                @Html.ValidationMessageFor(model => model.Authors, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.ISBN, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.ISBN)
                @Html.ValidationMessageFor(model => model.ISBN, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.WebSite, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.WebSite)
                @Html.ValidationMessageFor(model => model.WebSite, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("CategoryId", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryId, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Save" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to Books", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web Development/ASP.NET MVC/03. Kendo UI ASP.NET MVC Wrappers/KendoUI_ASP.NET_MVC_Wrappers/LibrarySystem/Views/LibrarySystem/Index.cshtml
@*@model IEnumerable<LibrarySystem.Models.Book>*@
@model IEnumerable<Kendo.Mvc.UI.TreeViewItemModel>

@{
    ViewBag.Title = "Books";
}

<h2>Books</h2>

@using (Html.BeginForm("Search", "LibrarySystem"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <input class="pull-right btn" type="submit" id="btnSearch" value="Search" />
    
    @(Html.Kendo().AutoComplete()
          .Name("books")
          .Filter("contains")
          .Placeholder("Search book...")
          .HtmlAttributes(new { @class = "pull-right" })
          .IgnoreCase(true)
          .MinLength(2)
        //.DataTextField("Authors")
        //.DataSource(source =>
        //{
        //    source.Read(read =>
        //    {
        //        read.Action("Search", "LibrarySystem")
        //            .Data("onAdditionalData");
        //    })
        //    .ServerFiltering(true);
        //})
    )
    @Html.Hidden("book", new { book = "" });
}

<script>
    //function onAdditionalData() {
    //    return {
    //        book: $("#books").val()
    //    };
    //}

    $('#btnSearch').click(function (e) {
        var value = $("#books").data("kendoAutoComplete").value();
        $("#book").val(value);
    });

    //$(document).ready(function () {
    //    var autoComplete = $("#books").data("kendoAutoComplete");
    //    autoComplete.bind("open", function (e) {
    //        e.preventDefault();
    //    });
    //    autoComplete.options.suggest = false;
    //});
</script>


<p>
    @Html.ActionLink("Create New", "Create")
</p>

@(Html.Kendo().TreeView()
    .Name("trvBooks")
    .BindTo(Model)
    .Events(ev => ev
        .Select(
        @<text>
            function(e) {
            var data = this.dataItem(e.node);
            $.post('@Url.Action("Details", "LibrarySystem")', {
                id: data.id
                }, function (data) {
                    $('body>.container').empty()
                    $('body>.container').append(data)
                    //alert("Changed " + data);
                });
            }
        </text>))
)

Web Development/ASP.NET MVC/03. Kendo UI ASP.NET MVC Wrappers/KendoUI_ASP.NET_MVC_Wrappers/LibrarySystem/Views/LibrarySystem/Search.cshtml
@model IEnumerable<LibrarySystem.Models.BookShortVM>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

@(Html.Kendo().ListView<LibrarySystem.Models.BookShortVM>(Model)
    .Name("listView")
    .TagName("ul")
    .ClientTemplateId("template")
    .BindTo(Model)
    .Selectable()
    .Events(ev => ev
            .Change(@<text>
                    function(e) {
                        var index = this.select().index();
                        dataItem = this.dataSource.view()[index];
                        $.post('@Url.Action("Details", "LibrarySystem")', {
                            id: dataItem.BookId
                            }, function (data) {
                                $('body>.container').empty()
                                $('body>.container').append(data)
                    });
                }
            </text>))
)

@{
    <script type="text/x-kendo-template" id="template">
        <li>#:Title# by #:Authors# (Category: #:CategoryName#)</li>
    </script>
}

<div>
    @Html.ActionLink("Back to Books", "Index")
</div>