Web Development/ASP.NET MVC/02. ASP.NET-MVC-Essentials/02. ASP.NET-MVC-Essentials/Information/Areas/Offer/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Information.Areas.Offer.Models;

namespace Information.Areas.Offer.Controllers
{
    public class OfferController : Controller
    {
        //
        // GET: /Offers/
        public ActionResult Index(OfferModel offerModel)
        {
            if (offerModel == null)
            {
                offerModel = new OfferModel();
            }

            offerModel.OfferTitles = new List<string>()
            {
                "offer 1",
                "offer 2",
                "offer 3",
                "offer 4",
                "offer 5"
            };

            return View(offerModel);
        }
	}
}

Web Development/ASP.NET MVC/02. ASP.NET-MVC-Essentials/02. ASP.NET-MVC-Essentials/Information/Controllers/TVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Information.Models;

namespace Information.Controllers
{
    public class TVController : Controller
    {
        //
        // GET: /TV/
        public ActionResult Index(TVmodel tvModel)
        {
            if (tvModel == null)
            {
                tvModel = new TVmodel();
            }

            tvModel.TvTitles = new List<string>()
            {
                "tv 1",
                "tv 2",
                "tv 3",
                "tv 4",
                "tv 5"
            };
            tvModel.Date = DateTime.Now;

            return View(tvModel);
        }
	}
}

Web Development/ASP.NET MVC/02. ASP.NET-MVC-Essentials/02. ASP.NET-MVC-Essentials/Information/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("News", "Index", "News", new { area = "" }, new { @class = "brand" })
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>@Html.ActionLink("Science", "Science", "News", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Culture", "Culture", "News", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("TVprogramm", "Index", "TV", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Offers", "Index", "Offer", new { area = "Offer" }, null)</li>

                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <div id="sidebar">
            @RenderSection("Sidebar", required: false)
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Actualno</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Web Development/ASP.NET MVC/02. ASP.NET-MVC-Essentials/02. ASP.NET-MVC-Essentials/Information/Views/Shared/_TVPartial.cshtml
@model Information.Models.TVmodel

<p>@Html.Label(Model.Date.ToString())</p>