Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/ViewModels/ActorDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LizardmanCinemas.ViewModels
{
    public class ActorDetails : DirectorDetails
    {
    }
}

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/ViewModels/DirectorDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LizardmanCinemas.ViewModels
{
    public class DirectorDetails
    {
        public int Id { get; set; }
        public string FullName { get; set; }

        public int Age { get; set; }

        public string Picture { get; set; }

        public IEnumerable<MovieDetails> Movies { get; set; }
    }
}

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LizardmanCinemas.Data;
using LizardmanCinemas.Models;
using LizardmanCinemas.ViewModels;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace LizardmanCinemas.Controllers
{
    public class ActorsController : BaseController
    {
        //private DataContext db = new DataContext();
        IUowData db;

        public ActorsController()
            : base(null)
        {
            db = new UowData();
        }

        public ActorsController(IUowData db)
            : base(db)
        {
        }

        // GET: /Actors/
        public ActionResult Index()
        {
            //// if using Kendo ListView
            return View(db.Actors.All().Select(ActorsShortViewModel.FromActor).ToList());
            
            //return View(db.Actors.All().ToList());
        }

        // DataSource for the Kendo ListView
        public ActionResult ReadActors([DataSourceRequest]DataSourceRequest request)
        {
            var actors = db.Actors.All().Select(ActorsShortViewModel.FromActor).AsEnumerable();

            DataSourceResult result = actors.ToDataSourceResult(request);

            return Json(result);
        }

        // For Search Result Window
        // GET: /Directors/DetailsView/5
        public ActionResult DetailsView(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.All().Include(d => d.Movies).FirstOrDefault(d => d.Id == id);
            if (actor == null)
            {
                return HttpNotFound();
            }

            var model = new ActorDetails()
            {
                FullName = actor.FirstName + " " + actor.LastName,
                Id = actor.Id,
                Age = actor.Age,
                Picture = actor.Picture,
                Movies = actor.Movies.Select(m => new MovieDetails()
                {
                    Title = m.Title,
                    CategoryName = m.Category.Name,
                    DetailsUrl = "/Movies/Details/" + m.Id,
                })
            };

            return PartialView("_ActorDetails", model);
        }

        // GET: /Actors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.GetById(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        public ActionResult ActorMovies(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.GetById(id);
            if (actor == null)
            {
                return HttpNotFound();
            }

            return PartialView("_ActorMovies", actor);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LizardmanCinemas.Data;
using LizardmanCinemas.Models;
using LizardmanCinemas.ViewModels;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using Microsoft.AspNet.Identity;

namespace LizardmanCinemas.Controllers
{
    public class MoviesController : Controller
    {
        private DataContext db = new DataContext();

        // GET: /Movies/
        public ActionResult Index()
        {
            return View(db.Movies.Select(MovieShortViewModel.FromMovie));
        }

        public ActionResult ReadMovies([DataSourceRequest]DataSourceRequest request)
        {
            var movies = db.Movies.Select(MovieShortViewModel.FromMovie);

            DataSourceResult result = movies.ToDataSourceResult(request);

            return Json(result);
        }

        // For Search Result Window
        // GET: /Directors/DetailsView/5
        public ActionResult DetailsView(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Include(d => d.Category).FirstOrDefault(d => d.Id == id);
            if (movie == null)
            {
                return HttpNotFound();
            }

            var model = new MovieDetails()
            {
                Title = movie.Title,
                Id = movie.Id,
                Poster = movie.Poster,
                CategoryName = movie.Category.Name,
                Year = movie.Year,
                DetailsUrl = "/Movies/Details/" + movie.Id,
            };

            return PartialView("_MovieDetailsPopUp", model);
        }

        // GET: /Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Include("Votes").Include("Votes.User").FirstOrDefault(x => x.Id == id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(int? id, string comment)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }

            if (!User.Identity.IsAuthenticated)
	        {
                return RedirectToAction("Index", "Home");
	        }

            var user = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            Comment newComment = new Comment
            {
                CommentText = comment,
                Movie = movie,
                User = user,
                CreatedOn = DateTime.Now
            };

            db.Comments.Add(newComment);
            movie.Comments.Add(newComment);
            db.SaveChanges();
            return RedirectToAction("Details/" + movie.Id);
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VoteUp(int? id)
        {
            return Votes(id, 1);
        }

        private ActionResult Votes(int? id, int islLke)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }

            var user = db.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            if (user == null)
            {
                return HttpNotFound();
            }

            var vote = db.Votes.FirstOrDefault(x => x.User.UserName == User.Identity.Name && x.MovieId == id);
            if (vote == null)
            {
                vote = new Vote();
            }

            vote.UserId = User.Identity.GetUserId();
            vote.Movie = movie;
            vote.IsLike = islLke;

            db.Votes.Add(vote);
            db.SaveChanges();

            return RedirectToAction("Details/" + movie.Id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VoteDown(int? id)
        {
            return Votes(id, -1);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_ActorDetails.cshtml
@model LizardmanCinemas.ViewModels.ActorDetails

@{
    ViewBag.Title = "Actor Details";

    var actorPicture = "/Content/Actors/" + Model.Picture;
}

<h3>
@Html.LabelFor(d => d.FullName, "Full Name", new { @class = "label label-info mylabel" })
@Html.DisplayFor(d => d.FullName)
    </h3>
<br />
<div class="movie-details">
    @if (String.IsNullOrEmpty(Model.Picture))
    {
        <div class="label label-info mylabel">
            Actor's picture is not available
        </div>
    }
    else
    {
        <img src=@actorPicture alt="picture" style="width: 90px; height: 135px" />
    }
</div><br />

<h3>
    @Html.LabelFor(d => d.Age, "Age", new { @class = "label label-info mylabel" })
    @if (Model.Age != 0)
    {
        @Html.DisplayFor(d => d.Age)
    }
    else
    {        
        @: No information
    }
</h3>


@foreach (var mov in Model.Movies)
{
    <h5><a href="@mov.DetailsUrl">@mov.Title</a><i>&nbsp;(@mov.CategoryName)</i></h5>
}

@Html.ActionLink("Details", "Details", "Actors", new { id = Model.Id }, new { @class="btn"})

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_ActorMovies.cshtml
@model LizardmanCinemas.Models.Actor

<h2>@string.Format("{0} {1}'s Movies", Model.FirstName, Model.LastName)</h2>

@foreach (var movie in Model.Movies)
{
    @Html.ActionLink(string.Format("{0} ({1})", movie.Title, movie.Year), "Details", "Movies", new { id = movie.Id }, null);
}

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_CategoryMovies.cshtml
@model IEnumerable<LizardmanCinemas.Models.Movie>

@{
    ViewBag.Title = "Movies";

    //var categoryName = Model.FirstOrDefault().Category.Name;
}

@*<h2>@categoryName</h2>*@

@if (Model.Count() != 0)
{
    foreach (var movie in Model)
    {
        string posterPath = "/Content/Posters/" + movie.Poster;
        <img src=@posterPath alt="poster" style="width: 180px; height: 270px" />
        @Html.ActionLink((movie.Title + " (" + movie.Year + ")"), "Details", "Movies", new { Area = "", id = movie.Id }, null)
        <hr />
    }
}
else
{
    <div class="movie-details">There are no movies in this category</div>
}

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_CategoryMoviesPopUp.cshtml
@model IEnumerable<LizardmanCinemas.ViewModels.MovieShortViewModel>

@{
    ViewBag.Title = "Movies";

    //var categoryName = Model.FirstOrDefault().Category.Name;
}

@*<h2>@categoryName</h2>*@

@if (Model.Count() != 0)
{
    foreach (var movie in Model)
    {
        string posterPath = "/Content/Posters/" + movie.Poster;
        <img src=@posterPath alt="poster" style="width: 90px; height: 135px" />
        @Html.ActionLink((movie.Title + " (" + movie.Year + ")"), "Details", "Movies", new { Area = "", id = movie.Id }, null)
        <hr />
    }
}
else
{
    <div class="movie-details">There are no movies in this category</div>
}

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_Comment.cshtml
@model  IEnumerable<LizardmanCinemas.ViewModels.MovieHomeVM>

<script type="text/x-kendo-tmpl" id="templateComments">
    <div class="movies-comments">
        <h4>Featured Comments for "#:Title#"</h4>
        <hr />
        @*#console.log(Comments)#*@
        #if(data.Comments != null){#
            #if(data.Comments.length == 0){#
                <p>Be the first to comment the "#:Title#" movie</p>
                #}else{#
                #for (var i = 0; i < data.Comments.length; i++){#
                    <div>
                        <em>
                            commented by
                            <span class="bold">#= data.Comments[i].Username #</span> on
                            <span class="bold">#= data.Comments[i].DisplayDate #</span>
                        </em>
                        <p>#= data.Comments[i].CommentText #</p>
                    </div>
                <hr />
                #}#
            #}#
        #}#
    </div>
</script>

<script type="text/javascript">
    var template3 = kendo.template($("#templateComments").html(), { useWithBlock: false });
</script>

@(Html.Kendo().ListView<LizardmanCinemas.ViewModels.MovieHomeVM>(Model)
    .Name("listView3")
    .TagName("div")
    .ClientTemplateId("templateComments")
    .DataSource(dataSource =>
    {
        dataSource.Read(read => read.Action("ReadComments", "Home"));
    })
)

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_DirectorDetails.cshtml
@model LizardmanCinemas.ViewModels.DirectorDetails

@{
    ViewBag.Title = "Director Details";

    var directorPicture = "/Content/Actors/" + Model.Picture;
}

@Html.LabelFor(d => d.FullName, "Full Name", new { @class = "label label-info mylabel" })
@Html.DisplayFor(d=> d.FullName)
<br />

<div class="movie-details">
    @if (String.IsNullOrEmpty(Model.Picture))
    {
        <div class="label label-info mylabel">
            Director's picture is not available
        </div>
    }
    else
    {
        <img src=@directorPicture alt="picture" style="width: 90px; height: 135px" />
    }
</div><br />

@Html.LabelFor(d => d.Age, "Age", new { @class = "label label-info mylabel" })
@Html.DisplayFor(d => d.Age)
<br />

@foreach (var mov in Model.Movies)
{
    <h5><a href="@mov.DetailsUrl">@mov.Title</a><i>&nbsp;(@mov.CategoryName)</i></h5>
}

@Html.ActionLink("Details", "Details", "Directors", new { id = Model.Id }, new { @class = "btn" })

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_DirectorMovies.cshtml
@model LizardmanCinemas.Models.Director

<h2>@string.Format("{0} {1}'s Movies", Model.FirstName, Model.LastName)</h2>

@foreach (var movie in Model.Movies)
{
    @Html.ActionLink(string.Format("{0} ({1})", movie.Title, movie.Year), "Details", "Movies", new { id = movie.Id }, null);
}

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_HomeActors.cshtml
@model IEnumerable<LizardmanCinemas.ViewModels.ActorsShortViewModel>

<h4>Featured Actors</h4>

<script type="text/x-kendo-tmpl" id="templateActors">
    <div class="movies">
        <a href="Actors/Details/#:Id#" style="width: 90px; height: 180px;">
            #if(data.Picture != null){#
            <img src="/Content/Actors/#: Picture #" alt="#:Name#" style="width: 90px; height: 180px; " />
            #}else{#
            <img src="/Content/Actors/noPoster.jpg" alt="#:Name#" style="width: 90px; height: 180px; " />
            #}#
            <h3>#:Name#</h3>
            <p>#:Name#</p>
        </a>
    </div>
</script>

<script type="text/javascript">
    var template = kendo.template($("#templateActors").html(), { useWithBlock: false });
</script>

<div class="demo-section">
    @(Html.Kendo().ListView<LizardmanCinemas.ViewModels.ActorsShortViewModel>(Model)
    .Name("listView")
    .TagName("div")
    .ClientTemplateId("template")
    .DataSource(dataSource =>
    {
        dataSource.Read(read => read.Action("ReadActors", "Actors"));
        //dataSource.PageSize(3);
    })
    //.Pageable()
    )
</div>

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LizardmanMovieDb</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/kendo")
    @Scripts.Render("~/bundles/kendo")
    @*<script src="~/Scripts/jquery-1.8.2.min.js"></script>*@
    @*<script type="text/javascript">
            jQuery.noConflict();
        </script>*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("LizardmanMoviesDb", "Index", "Home", new { area = "" }, new { @class = "brand" })*@
                <a href='@Url.Action("index", "Home", new { area = "" })' class="brand">
                    <img src='@Url.Content("~/Content/Images/lizard.png")' id="lizard" />
                </a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>@Html.ActionLink("Movies", "Index", "Movies", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Actors", "Index", "Actors", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Directors", "Index", "Directors", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Categories", "Index", "Categories", new { area = "" }, null)</li>
                        @if (User.IsInRole("Admin"))
                        {
                        <li class="dropdown">
                            @Html.ActionLink("Admin", "Index", "MovieAdmin", new { area = "Admin" }, new { @class = "dropdown-toggle", data_toggle = "dropdown" })
                            <ul class="dropdown-menu lizard-dropdown-menu">
                                <li class="lizard-dropdown">@Html.ActionLink("Movies", "Index", "MovieAdmin", new { area = "Admin" }, null)</li>
                                <li class="lizard-dropdown">@Html.ActionLink("Categories", "Index", "CategoryAdmin", new { area = "Admin" }, null)</li>
                                <li class="lizard-dropdown">@Html.ActionLink("Actors", "Index", "ActorAdmin", new { area = "Admin" }, null)</li>
                                <li class="lizard-dropdown">@Html.ActionLink("Directors", "Index", "DirectorAdmin", new { area = "Admin" }, null)</li>
                            </ul>
                        </li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
            <div class="container">
                @Html.Partial("_SearchNavbar")
            </div>
        </div>
    </div>

    @if (HttpContext.Current.Request.Url.AbsoluteUri == "http://localhost:3960/")
    {
        <div id="player" style="position: fixed; z-index: -99; width: 100%; height: 100%">
            <iframe frameborder="0" height="100%" width="100%"
                    src="https://youtube.com/embed/YsOl6kIDDOc?hd=1&autoplay=1&controls=0&showinfo=0&rel=0&autohide=1&modestbranding=1&end=30&loop=1"></iframe>
        </div>
    }

    <script>
        //// 2. This code loads the IFrame Player API code asynchronously.
        //var tag = document.createElement('script');
        //tag.src = "http://www.youtube.com/player_api";
        //var firstScriptTag = document.getElementsByTagName('script')[0];
        //firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        //// 3. This function creates an <iframe> (and YouTube player)
        ////    after the API code downloads.
        //var player;
        //function onYouTubePlayerAPIReady() {
        //    player = new YT.Player('player', {
        //        playerVars: { 'autoplay': 1, 'controls': 0, 'rel': 0, 'autohide': 1, 'showinfo': 0, 'modestbranding': 1, 'wmode': 'opaque' },
        //        videoId: '3KumjBXHdzY',
        //        events: {
        //            'onReady': onPlayerReady
        //        }
        //    });
        //}

        //// 4. The API will call this function when the video player is ready.
        //function onPlayerReady(event) {
        //    event.target.mute();
        //}
    </script>

    <div class="container" id="container">
        <div id="error" class="alert alert-error" style="display:none"></div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LizardmanMovieDb</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_MovieDestails.cshtml
@using Microsoft.AspNet.Identity
@model LizardmanCinemas.Models.Movie

@{
    var directorName = string.Format("{0} {1}", Model.Director.FirstName, Model.Director.LastName);

    var posterPath = "/Content/Posters/" + Model.Poster;
}

<div>
    <div class="movie-title">@Html.DisplayFor(model => model.Title)</div>

    <div class="movie-details"><img src=@posterPath alt="poster" style="width: 180px; height: 270px" /></div>
    
    @if (!string.IsNullOrEmpty(Model.Trailer))
{
    <div class="movie-details">
        <iframe width="420" height="315" src="//www.youtube.com/embed/@Model.Trailer.Split('=')[1]" frameborder="0" allowfullscreen></iframe>
    </div>
}

    <div class="movie-details">Director: @Html.ActionLink(directorName, "Details", "Directors", new { Area = "", id = Model.Director.Id }, null)</div>

    <div class="movie-details">
        Artists:
        <ul class="artists-list">
            @foreach (var actor in Model.Actors)
            {
                <li>
                    @Html.ActionLink((actor.FirstName + " " + actor.LastName), "Details", "Actors", new { Area = "", id = actor.Id }, null)
                </li>
            }
        </ul>
    </div>
    <div class="movie-details">Year: @Html.DisplayFor(model => model.Year)</div>
    <div class="movie-details">Duration: @Html.DisplayFor(model => model.Duration) minutes</div>
    <div class="movie-details">Country: @Html.DisplayFor(model => model.Country.Name)</div>
    <div class="movie-details">Category: @Html.ActionLink(@Model.Category.Name, "Details", "Categories", new { Area = "", id = Model.Category.Id }, null)</div>

    <div class="movie-details">
        Trailer:
        @if (String.IsNullOrEmpty(Model.Trailer))
        {
            @: not available
        }
        else
        {
            @Html.DisplayFor(model => model.Trailer)
        }
    </div>

    <div class="movie-details">
        Parent Guide:
        @if (Model.ParentsGuide == LizardmanCinemas.Models.ParentsGuide.Under12)
        {
            <img src="~/Content/ParentsGuide/PEGI_12.png" alt="Under 12" style="width: 40px; height:40px" />
        }
        else if (Model.ParentsGuide == LizardmanCinemas.Models.ParentsGuide.Under16)
        {
            <img src="~/Content/ParentsGuide/PEGI_16.png" alt="Under 16" />
        }
        else if (Model.ParentsGuide == LizardmanCinemas.Models.ParentsGuide.Under18)
        {
            <img src="~/Content/ParentsGuide/PEGI_18.png" alt="Under 18" />
        }
    </div>
    <p class="movie-details">
        Description:
        @Html.DisplayFor(model => model.Description)
    </p>
    @{
        var count = Model.Votes.Where(x => x.MovieId == Model.Id).Sum(x => x.IsLike);
    }
    <div class="movie-details">Votes: @count</div>
</div>

<div>
    @if (User.Identity.IsAuthenticated)
    {
        if (!Model.Votes.Any(x => x.UserId == User.Identity.GetUserId() && x.MovieId == Model.Id))
        {
            using (Html.BeginForm("VoteUp", "Movies", new {id = Model.Id}, FormMethod.Post, new {style = "display: inline-block; margin-right: 10px;"}))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <input type="submit" class="btn" value="Vote Up" />
            }

            using (Html.BeginForm("VoteDown", "Movies", new {id = Model.Id}, FormMethod.Post, new {style = "display: inline-block"}))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <input type="submit" class="btn" value="Vote Down" />
            }
        }
    }
    else
    {
        <p class="lead">Login to vote for this film</p>
    }
</div>

<div class="movie-comments">
    <h4>Comments</h4>
    <hr />

    @if (Model.Comments.Count == 0)
    {
        <p>Be the first to comment this film</p>
    }
    else
    {
        foreach (var comment in Model.Comments)
        {
            <p>@comment.CommentText</p>
            <div class="pull-left">
                <em>
                    commented by <span class="bold">@Html.ActionLink(comment.User.UserName, "Details", "Users", new { id = comment.User.Id }, null)</span>
                    on @string.Format("{0:dd.MM.yyyy}", comment.CreatedOn)
                </em>
            </div>
            <hr />
        }
    }
</div>


@using (Html.BeginForm("AddComment", "Movies", new { id = Model.Id }, FormMethod.Post, null))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <legend>Add Comments</legend>

    if (User.Identity.IsAuthenticated)
    {
        <label for="movie-comments"></label>
        <input type="text" id="movie-comments" name="comment" /> <br />
        <input type="submit" class="btn" value="Add" />
    }
    else
    {
        <p class="lead">Login to add comments for this film</p>
    }
}


<p>
    @Html.ActionLink("Back to Movies", "Index", null, new { @class = "btn" })
</p>

Web Development/ASP.NET MVC/TeamWork/LizardmanCinemas/LizardmanCinemas/LizardmanCinemas/Views/Shared/_MovieDetailsPopUp.cshtml
@model LizardmanCinemas.ViewModels.MovieDetails

@{
    ViewBag.Title = "Actor Details";

    var moviePoster = "/Content/Posters/" + Model.Poster;

    var titleAndYear = Model.Title + " " + Model.Year;
}

<h3>
    @Html.LabelFor(d => d.Title, "Title", new { @class = "label label-info mylabel" })
    @Html.DisplayFor(d => titleAndYear)
</h3>
<br />
<div class="movie-details">
    @if (String.IsNullOrEmpty(Model.Poster))
    {
        <div class="label label-info mylabel">
            Movie's poster is not available
        </div>
    }
    else
    {
        <img src=@moviePoster alt="picture" style="width: 90px; height: 135px" />
    }
</div><br />

<h3>
    @Html.LabelFor(d => d.CategoryName, "Category", new { @class = "label label-info mylabel" })
    @Html.DisplayFor(d => d.CategoryName)
</h3>

@Html.ActionLink("Details", "Details", "Movies", new { id = Model.Id }, new { @class = "btn" })